#!/usr/bin/env bash

#  http://github.com/thewoolleyman/boxbuilder
#  Copyright (c) 2010 Chad Woolley - The MIT License

boxbuilder_debug=${boxbuilder_debug:-true} # Set this to true to debug failing tests

source $(dirname $0)/test_helper

if [[ $boxbuilder_debug = true ]]; then
  export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  set –o verbose
  set -o xtrace
fi

set -o errexit
set -o errtrace
set -o noclobber
set -o nounset
set -o pipefail

_log_prefix="BOXBUILDER - $BASH_SOURCE:"

function onexit() {
  local exit_status=${1:-$?}
  if [[ $exit_status != 0 ]]; then
    _error_line="error trapped."
  else
    _error_line=''
  fi
  if [[ $(type -t onexit_hook) = 'function' ]]; then
    onexit_hook
  fi
  echo "$_log_prefix $_error_line Exiting $0 with $exit_status"
  exit $exit_status
}

trap onexit HUP INT QUIT TERM ERR

exec_remotely_quiet() {
  local arg_array i rc
  for arg; do
    arg_array[i++]=$(printf %q "$arg")
  done
  ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -i $boxbuilder_keypair $boxbuilder_user@$boxbuilder_built_instance_host "$@"
}

onexit_hook() {
  if [[ $boxbuilder_terminate_ec2_resources = true ]]; then
    if [[ -n $boxbuilder_built_instance_id ]]; then
      # delete instance
      _terminate_instances_result=$(ec2-terminate-instances --private-key $EC2_PRIVATE_KEY --cert $EC2_CERT "$boxbuilder_built_instance_id")
      echo "$_log_prefix ec2-terminate-instances result for instance $boxbuilder_built_instance_id:"
      echo "$(sed -n l <<< $_terminate_instances_result)"
    fi

    if [[ -n $boxbuilder_created_ami_id ]]; then
      # delete AMI
      _deregister_result=$(ec2-deregister --private-key $EC2_PRIVATE_KEY --cert $EC2_CERT "$boxbuilder_created_ami_id")
      echo "$_log_prefix ec2-deregister result for image $boxbuilder_created_ami_id:"
      echo "$(sed -n l <<< $_deregister_result)"
    fi

    if [[ -n $boxbuilder_created_ami_ebs_snapshot_id ]]; then
      # delete snapshot
      _delete_snapshot_result=$(ec2-delete-snapshot --private-key $EC2_PRIVATE_KEY --cert $EC2_CERT "$boxbuilder_created_ami_ebs_snapshot_id")
      echo "$_log_prefix ec2-delete-snapshot result for snapshot $boxbuilder_created_ami_ebs_snapshot_id:"
      echo "$(sed -n l <<< $_delete_snapshot_result)"
    fi
  fi
}

setup() {
  export boxbuilder_debug

  if [ -e $HOME/.boxbuilder_testrc ]; then
    # Set test vars
    source $HOME/.boxbuilder_testrc # don't use real .boxbuilderrc file, we don't want to pollute it with test vars
  fi
  export PATH=$EC2_HOME/bin:$PATH # TODO: this should be automatic, see tracker stories
  boxbuilder_ec2_resource_tag='boxbuilder_temp_resource_safe_to_terminate'
  # TODO: grep boxbuilder_keypair value out of boxbuilder_remote_build_ami output
  boxbuilder_keypair=${boxbuilder_keypair:?Please set 'boxbuilder_keypair' to the path of your ssh private key file}
  boxbuilder_user=${boxbuilder_user:-'ubuntu'}
  boxbuilder_dir="$(dirname $0)/.."
  boxbuilder_terminate_ec2_resources=${boxbuilder_terminate_ec2_resources:-true}
  boxbuilder_config="export boxbuilder_ami_prefix=$boxbuilder_ec2_resource_tag; export boxbuilder_terminate_ec2_resources=$boxbuilder_terminate_ec2_resources; export boxbuilder_user=$boxbuilder_user"
  export boxbuilder_config

  # initialize local script variables to avoid unbound variable errors
  # in onexit hook which terminates resources if test fails and they are not set
  boxbuilder_built_instance_id=${boxbuilder_built_instance_id:-''}
  boxbuilder_created_ami_id=${boxbuilder_created_ami_id:-''}
  boxbuilder_created_ami_ebs_snapshot_id=${boxbuilder_created_ami_ebs_snapshot_id:-''}

  set +o xtrace # even if boxbuilder_debug is on, always turn off tracing
                # while running build and grabbing output.
                # dumping entire build output makes test output huge and confusing

  # Invoke boxbuilder_remote_build_ami to exercise all boxbuilder scripts except boxbuilder_bootstrap
  boxbuilder_remote_build_ami_output=$($boxbuilder_dir/boxbuilder_remote_build_ami)

  # Start built AMI
  echo; echo; echo
  echo "-------- BEGIN OUTPUT OF boxbuilder_remote_build_ami --------"
  echo "$boxbuilder_remote_build_ami_output"
  echo "-------- END OUTPUT OF boxbuilder_remote_build_ami --------"
  echo; echo; echo

  ami_vars=$(echo "$boxbuilder_remote_build_ami_output" | grep -e '^boxbuilder_created_ami_')

  if [[ $boxbuilder_debug = true ]]; then
    # turn back on tracing if we are debugging
    set -o xtrace
  fi

  echo "$ami_vars"
  eval $ami_vars
  # Strip carriage returns which show up after eval
  boxbuilder_created_ami_id="$(tr -d '\r' < <(echo $boxbuilder_created_ami_id) )"
  boxbuilder_created_ami_ebs_snapshot_id="$(tr -d '\r' < <(echo $boxbuilder_created_ami_ebs_snapshot_id) )"

  boxbuilder_built_instance_id=$(ec2-run-instances --private-key $EC2_PRIVATE_KEY --cert $EC2_CERT \
    --key "$EC2_KEYPAIR_NAME" \
    --availability-zone us-east-1a \
    --instance-type "m1.large" \
    "$boxbuilder_created_ami_id" \
    -d "$boxbuilder_ec2_resource_tag" \
    | egrep ^INSTANCE | cut -f2)
  while boxbuilder_built_instance_host=$(ec2-describe-instances --private-key $EC2_PRIVATE_KEY --cert $EC2_CERT \
     "$boxbuilder_built_instance_id" | \
    egrep ^INSTANCE | cut -f4) && [[ -z $boxbuilder_built_instance_host ]]; do
      echo -n .
      sleep 5
  done
  echo "$_log_prefix Got hostname $boxbuilder_built_instance_host for instance $boxbuilder_built_instance_id"
  echo "$_log_prefix Waiting for ssh connectivity to $boxbuilder_built_instance_host ..."
  while ssh_up=$(ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -i $EC2_KEYPAIR $boxbuilder_user@$boxbuilder_built_instance_host "echo 'ssh up'"); [[ "$ssh_up" != "ssh up" ]]; do
    echo "$_log_prefix SSH connect response from $boxbuilder_built_instance_host: $ssh_up"
    echo "$_log_prefix Trying to SSH to $boxbuilder_built_instance_host again after 3 seconds..."
    sleep 5
  done
}

test_can_log_in_as_user() {
  remote_user=$(exec_remotely_quiet "whoami")
  assert_equal $boxbuilder_user $remote_user
}

test_can_install_rvm() {
  rvm_info=$(exec_remotely_quiet "rvm info | head -n 1")
  assert_match 'ruby' $rvm_info
}

test_can_set_up_and_run_chef() {
  example_main_touchfile_contents=$(exec_remotely_quiet 'cat $HOME/.tmp_boxbuilder_example_main_chef_cookbook.touchfile')
  assert_equal 'boxbuilder_example_main_chef_config_value' $example_main_touchfile_contents
  example_dependency_touchfile_contents=$(exec_remotely_quiet 'cat $HOME/.tmp_boxbuilder_example_dependency_chef_cookbook.touchfile')
  assert_match 'boxbuilder_example_dependency_chef_config_set_from_main_value' $example_dependency_touchfile_contents
}

test_boxbuilder_remote_bootstrap() {
  # Test boxbuilder_remote_bootstrap by running it on instance started
  # from built AMI 
  overridden_touchfile_value='boxbuilder_example_main_chef_config_value_overridden'
  boxbuilder_config="export boxbuilder_example_main_chef_config_key='$overridden_touchfile_value'"
  export boxbuilder_config
  export boxbuilder_keypair
  export boxbuilder_user
  boxbuilder_host=$boxbuilder_built_instance_host
  export boxbuilder_host
  boxbuilder_remote_bootstrap_output=$($boxbuilder_dir/boxbuilder_remote_bootstrap)
  echo; echo; echo
  echo "-------- BEGIN OUTPUT OF boxbuilder_remote_bootstrap --------"
  echo "$boxbuilder_remote_bootstrap_output"
  echo "-------- END OUTPUT OF boxbuilder_remote_bootstrap --------"
  echo; echo; echo

  example_main_touchfile_contents=$(exec_remotely_quiet 'cat $HOME/.tmp_boxbuilder_example_main_chef_cookbook.touchfile')
  assert_equal $overridden_touchfile_value $example_main_touchfile_contents
}

suite_centos() {
  echo "$_log_prefix Starting tests on CentOS ..."
  boxbuilder_user=${boxbuilder_user:-"root"}
  boxbuilder_builder_instance_ami_id=${boxbuilder_builder_instance_ami_id:-"ami-4d42a924"}
  setup
  test_can_log_in_as_user
  test_can_install_rvm
  test_can_set_up_and_run_chef
  test_boxbuilder_remote_bootstrap
  echo "$_log_prefix All tests passed successfully on CentOS"
}

suite_ubuntu() {
  echo "$_log_prefix Starting tests on Ubuntu ..."
  boxbuilder_user=${boxbuilder_user:-"ubuntu"}
  boxbuilder_builder_instance_ami_id=${boxbuilder_builder_instance_ami_id:-"ami-4b4ba522"}
  setup
  test_can_log_in_as_user
  test_can_install_rvm
  test_can_set_up_and_run_chef
  test_boxbuilder_remote_bootstrap
  echo "$_log_prefix All tests passed successfully on Ubuntu"
}

suite() {
  echo "$_log_prefix Starting tests ..."
  suite_ubuntu
  echo "$_log_prefix All tests passed successfully"
}


suite
onexit
