#!/usr/bin/env bash

#  http://github.com/thewoolleyman/boxbuilder
#  Copyright (c) 2010 Chad Woolley - The MIT License

export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

set -o errexit
set -o noclobber
set -o nounset
set -o pipefail
set –o verbose
set -o xtrace

handle_error() {
  echo "BOXBUILDER - test_helper: error on line $LINENO"
  exit 1 # TODO: return original error code.  how?
}

trap handle_error ERR EXIT INT TERM

assert_equal() {
  set +o nounset
  if [[ ! $1 = $2 ]]; then
    echo "Expected $2 to be equal to $1"
    echo "Failure at line, method, file:" `caller 0`
    set -o nounset
    return 1
  fi
  set -o nounset
}

assert_match() {
  set +o errexit
  set +o nounset
  echo $2 | grep -e $1
  if [[ ! $? = 0 ]]; then
    echo "Expected $2 to match $1"
    echo "Failure at line, method, file:" `caller 0`
    set -o nounset
    return 1
  fi
  set -o nounset
  set -o errexit
}
