#!/usr/bin/env bash

#  http://github.com/thewoolleyman/boxbuilder
#  Copyright (c) 2010 Chad Woolley - The MIT License

set -o noclobber
set -e
set -o pipefail
set -o nounset
trap 'echo BOXBUILDER - boxbuilder_remote_bootstrap: error on line $LINENO' ERR

setup() {
  . `dirname $0`/boxbuilder_utils
  . $HOME/.boxbuilderrc
  boxbuilder_keypair=${boxbuilder_keypair:?Please set 'boxbuilder_keypair' to the path of your ssh private key file}
  boxbuilder_user=${boxbuilder_user:?Please set 'boxbuilder_user' to the ssh user on the box you are using to test}
  boxbuilder_host=${boxbuilder_host:?Please set 'boxbuilder_host' to the hostname or IP of the box you are using to test}
  boxbuilder_bootstrap_url=${boxbuilder_bootstrap_url:-http://github.com/thewoolleyman/boxbuilder/raw/master/boxbuilder_bootstrap}
  boxbuilder_config=${boxbuilder_config:-'export boxbuilder_config_placeholder=boxbuilder_config_placeholder'}
}

remote_bootstrap() {
  echo "BOXBUILDER: Performing custom setup on $boxbuilder_host using script at $boxbuilder_bootstrap_url ..."
  boxbuilder_bootstrap_script=/tmp/${boxbuilder_bootstrap_url##*/} # grabs last path component of url to use as script name
  echo "BOXBUILDER: Downloading custom setup script $boxbuilder_bootstrap_script from $boxbuilder_bootstrap_url ..."
  exec_remotely "wget -O $boxbuilder_bootstrap_script $boxbuilder_bootstrap_url"
  while exists=$(exec_remotely_quiet "if [[ -e $boxbuilder_bootstrap_script ]] ; then echo exists; fi"); test "$exists" != "exists" ; do
    echo "BOXBUILDER: Waiting for curl to finish downloading $boxbuilder_bootstrap_script from $boxbuilder_bootstrap_url ..."
    sleep 3
  done
  echo "BOXBUILDER: $boxbuilder_bootstrap_url successfully downloaded to $boxbuilder_bootstrap_script ..."

  echo "BOXBUILDER: Changing permissions on $boxbuilder_bootstrap_script ..."
  exec_remotely "chmod a+x $boxbuilder_bootstrap_script"
  echo "BOXBUILDER: Running $boxbuilder_bootstrap_script ..."
  exec_remotely "$boxbuilder_config && $boxbuilder_bootstrap_script"
}

run() {
  setup
  remote_bootstrap
}

run