#!/usr/bin/env bash

#  http://github.com/thewoolleyman/boxbuilder
#  Copyright (c) 2010 Chad Woolley - The MIT License

boxbuilder_debug=${boxbuilder_debug:-false}

if [[ $boxbuilder_debug = true ]]; then
  export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  set -o verbose
  set -o xtrace
fi

set -o errexit
set -o errtrace
set -o noclobber
set -o nounset
set -o pipefail

_log_prefix="BOXBUILDER - $BASH_SOURCE:"

function onexit() {
  local exit_status=${1:-$?}
  if [[ $exit_status != 0 ]]; then
    _error_line="error trapped."
  else
    _error_line=''
  fi
  if [[ $(type -t onexit_hook) = 'function' ]]; then
    onexit_hook
  fi
  echo "$_log_prefix $_error_line Exiting $0 with $exit_status"
  exit $exit_status
}

function disable_error_checking() {
  trap - ERR
  set +o errexit
}

function enable_error_checking() {
  trap onexit ERR
  set -o errexit
}

trap onexit HUP INT QUIT TERM ERR

exec_remotely() {
  local arg_array i rc
  for arg; do
    arg_array[i++]=$(printf %q "$arg")
  done
  echo "ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -i $boxbuilder_keypair $boxbuilder_user@$boxbuilder_host \"$@\""
  ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -i $boxbuilder_keypair $boxbuilder_user@$boxbuilder_host "$@"
}

exec_remotely_quiet() {
  local arg_array i rc
  for arg; do
    arg_array[i++]=$(printf %q "$arg")
  done
  # echo "ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -i $boxbuilder_keypair $boxbuilder_user@$boxbuilder_host \"$@\""
  ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -i $boxbuilder_keypair $boxbuilder_user@$boxbuilder_host "$@"
}

exec_remotely_pseudo_tty() {
  local arg_array i rc
  for arg; do
    arg_array[i++]=$(printf %q "$arg")
  done
  echo "ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -t -i $boxbuilder_keypair $boxbuilder_user@$boxbuilder_host \"$@\""
  ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -t -i $boxbuilder_keypair $boxbuilder_user@$boxbuilder_host "$@"
}

exec_remotely_quiet_root() {
  local arg_array i rc
  for arg; do
    arg_array[i++]=$(printf %q "$arg")
  done
  ssh -o 'StrictHostKeyChecking no' -o 'PasswordAuthentication no' -i $boxbuilder_keypair root@$boxbuilder_host "$@"
}

grant_nopasswd_sudo_access() {
  echo "$_log_prefix  Checking no-password sudo access for 'admin' group on host $boxbuilder_host and adding if necessary.  If prompted, please type your password, or ctrl-c to abort..."
  if ! exec_remotely_quiet_root 'grep -e "%admin.*ALL.*=.*NOPASSWD.*:.*ALL" /etc/sudoers)'; then
    echo "$_log_prefix  Giving user $boxbuilder_user NO PASSWORD sudo privileges"
    exec_remotely_quiet_root "rm -f /tmp/sudoers.new"
    exec_remotely_quiet_root "cp /etc/sudoers /etc/sudoers.bak"
    exec_remotely_quiet_root "cp /etc/sudoers /tmp/sudoers.new"
    _new_sudoers_line="%admin ALL=NOPASSWD: ALL"
    exec_remotely_quiet_root "sh -c 'echo \"$_new_sudoers_line\" >> /tmp/sudoers.new'"
    if ! exec_remotely_quiet_root "visudo -c -s -f /tmp/sudoers.new"; then
      echo "$_log_prefix  error on line $LINENO -: Syntax error in /tmp/sudoers.new on host $boxbuilder_host.  Please manually add this entry using visudo: $_new_sudoers_line"
      return 1
    fi
    exec_remotely_quiet_root "cp /tmp/sudoers.new /etc/sudoers"
  else
    echo "$_log_prefix  admin group already appears to have NOPASSWD sudo access."
  fi
}

ensure_boxbuilder_user_exists() {
  echo "$_log_prefix  Ensuring boxbuilder_user '$boxbuilder_user' exists on $boxbuilder_host ..."
  if [[ $boxbuilder_user = 'root' ]]; then
    echo "$_log_prefix  boxbuilder_user cannot be root.  Please set \
boxbuilder_user to a non-root user.  If it does not exist, it will be \
automatically created if there is a valid no-passphrase SSH key to the root user ..."
    return 1
  fi
  if exec_remotely 'id'; then
    echo "$_log_prefix  boxbuilder_user '$boxbuilder_user' already exists on $boxbuilder_host ..."
    return 0
  fi
  echo "$_log_prefix  boxbuilder_user '$boxbuilder_user' does not exist, checking for root access on $boxbuilder_host to automatically create it ..."
  if ! exec_remotely_quiet_root 'id'; then
    echo "$_log_prefix  No root SSH access on $boxbuilder_host, cannot automatically create boxbuilder_user $boxbuilder_user.  Create manually with valid SSH access or give SSH access to root ..."
    return 1
  fi
  echo "$_log_prefix  SSH access exists for root ..."
  echo "$_log_prefix  Ensuring 'admin' group exists ..."
  exec_remotely_quiet_root "groupadd -f admin"
  _admin_gid=$(exec_remotely_quiet_root "grep 'admin' /etc/group | cut -d: -f3")
  echo "$_log_prefix  Automatically creating '$boxbuilder_user' user ..."
  if exec_remotely_quiet_root "id $boxbuilder_user"; then
    echo "$_log_prefix  '$boxbuilder_user' user already exists, not re-adding ..."
  else
    exec_remotely_quiet_root "useradd $boxbuilder_user -m -g $_admin_gid"
  fi
  echo "$_log_prefix  Finding home dir for '$boxbuilder_user' user ..."
  _boxbuilder_user_home=$(exec_remotely_quiet_root "su - $boxbuilder_user -c 'echo \$HOME'")
  echo "$_log_prefix  Copying SSH authorized keys from root to '$boxbuilder_user' user's home dir with correct ownership ..."
  exec_remotely_quiet_root "mkdir -p '$_boxbuilder_user_home/.ssh/'"
  exec_remotely_quiet_root "cp '.ssh/authorized_keys' '$_boxbuilder_user_home/.ssh/'"
  exec_remotely_quiet_root "chown -R $boxbuilder_user '$_boxbuilder_user_home/.ssh'"
  if exec_remotely 'id'; then
    echo "$_log_prefix  boxbuilder_user '$boxbuilder_user' successfully created on $boxbuilder_host ..."
  else
    echo "$_log_prefix  boxbuilder_user '$boxbuilder_user' was NOT successfully created on $boxbuilder_host - something went wrong :( - try setting boxbuilder_debug=true ..."
    return 1
  fi
  grant_nopasswd_sudo_access
}

setup() {
  echo "$_log_prefix  Environment variable setup ..."
  if [ -e $HOME/.boxbuilder_remote_bootstraprc ]; then
    source $HOME/.boxbuilder_remote_bootstraprc
  fi
  boxbuilder_config=${boxbuilder_config:-'export boxbuilder_config_placeholder_from_boxbuilder_remote_bootstrap=boxbuilder_config_placeholder_from_boxbuilder_remote_bootstrap'}
  eval $boxbuilder_config
  boxbuilder_keypair=${boxbuilder_keypair:?"Please set 'boxbuilder_keypair' to the path of your ssh private key file"}
  boxbuilder_user=${boxbuilder_user:?"Please set 'boxbuilder_user' to the ssh user on the box being built"}
  boxbuilder_host=${boxbuilder_host:?"Please set 'boxbuilder_host' to the hostname or IP of the box being built"}
  boxbuilder_bootstrap_url=${boxbuilder_bootstrap_url:-"http://github.com/thewoolleyman/boxbuilder/raw/master/boxbuilder_bootstrap"}

  echo "$_log_prefix  Finished environment variable setup:"
  echo "boxbuilder_config=$boxbuilder_config"
  # TODO: Add all env vars which are directly used by this script
}

remote_bootstrap() {
  _boxbuilder_bootstrap_script=/tmp/${boxbuilder_bootstrap_url##*/} # grabs last path component of url to use as script name
  echo "$_log_prefix Downloading $boxbuilder_bootstrap_url to $_boxbuilder_bootstrap_script on $boxbuilder_host ..."
  exec_remotely "wget -O $_boxbuilder_bootstrap_script $boxbuilder_bootstrap_url"
  while exists=$(exec_remotely_quiet "if [[ -e $_boxbuilder_bootstrap_script ]] ; then echo exists; fi"); [[ "$exists" != "exists" ]]; do
    echo "$_log_prefix Waiting for wget to finish downloading $boxbuilder_bootstrap_url to $_boxbuilder_bootstrap_script on $boxbuilder_host ..."
    sleep 5
  done
  echo "$_log_prefix $boxbuilder_bootstrap_url successfully downloaded to $_boxbuilder_bootstrap_script on $boxbuilder_host ..."

  echo "$_log_prefix Changing permissions on $_boxbuilder_bootstrap_script on $boxbuilder_host ..."
  exec_remotely "chmod a+x $_boxbuilder_bootstrap_script"
  echo "$_log_prefix Running $_boxbuilder_bootstrap_script on $boxbuilder_host ..."
  exec_remotely_pseudo_tty "export boxbuilder_config='$boxbuilder_config' \
    && export boxbuilder_debug=$boxbuilder_debug \
    && $_boxbuilder_bootstrap_script"
}

run() {
  echo "$_log_prefix Starting ..."
  setup
  ensure_boxbuilder_user_exists
  remote_bootstrap
  echo "$_log_prefix Finished and exiting successfully"
}

run
onexit
